### ISSUE TITLE
api_spec.rb est obsolète

### ISSUE THREAD

**Issue by cycojesus** [laclasse-com/service-publipostage#15]
le mettre à jour

**Comment by hquenin** [comment]
j'ai besoin de beaucoup de précision sur cette issue

dois je faire tous les tests pour api.rb ?

**Comment by cycojesus** [comment]
- Il faut utiliser laclasse-common à la place de la lib annuaire qui est obsolète.
- Il faut compléter les tests pour couvrir ce qui concerne les publipostages (appels avec `:service_annuaire_publipostage` ) :
  - lister tous
  - en récupérer un 
  - en créer un
  - en modifier un si la fonction a été implémentée
  - en supprimer un
  - en récupérer le pdf
