### ISSUE TITLE
problème pour taper du texte dans le message

### ISSUE THREAD

**Issue by Bruno-o** [laclasse-com/service-publipostage#41]
Impossible d'écrire du texte dans le message tant que l'on a pas choisi "Formats" ou "taille de la police" sur Ipad et version chrome

**Comment by Pilooz** [comment]
Je ne reproduit pas ce porblème ? Sur quel navigateur ?  Sur tablette ?

**Comment by Bruno-o** [comment]
Sur Ipad retina et chrome

B.


Le 17/09/2015 09:38, Pierre-Gilles Levallois a écrit :
>
> Je ne reproduit pas ce porblème ? Sur quel navigateur ? Sur tablette ?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/laclasse-com/service-publipostage/issues/41#issuecomment-140993161>.
>



---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus
