### ISSUE TITLE
Test V3 - 2016 : Ecrire à tous - contrôle sur la sélection des profils des destinataires

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-publipostage#57]
Est-il normal que sur le type de message écrire à tous, à l'étape 2, lors de la sélection des destinataires, le choix des profils soit obligatoire pour pouvoir passer à l'étape suivante ?

**Comment by cycojesus** [comment]
oui

**Comment by TestsCGI** [comment]
OK
