### ISSUE TITLE
Test V3 - 2016 : Affichage des publipostages diffusés en mode actualité sur le portail

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-publipostage#59]
Où peut être consulté le message de type "écrire à tous" créé avec le service publipostage et diffusé au format actualité dans le portail ?
Le message de confirmation de l'étape 5 de création du publipostage est : "Le message est créé ! Le message a été diffusé en ligne sur la page info famille" Quelle est cette page info famille ?

**Comment by TestsCGI** [comment]
Le message rédigé est bien consultable sur le volet gauche du portail.
La date de publication est bien celle de diffusion.
L'image insérée dans le message ne s'affiche pas.
Le même message est mis à jour : les enseignants sont les seuls destinataires.
Le publipostage initial reste visible par tous et la mise à jour n'est pas faite pour un utilisateur enseignant

**Comment by cycojesus** [comment]
- bug affichage image ?
- on ne mets pas à jour un publipostage, on ne peut qu'en refaire un nouveau basé sur un précédent
