### ISSUE TITLE
Test V3 - 2016 : étape 3 - écrire le message - mise à jour du champ signature lors du publipostage

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-publipostage#61]
L'insertion du champ [signature] n'implique pas de mise à jour du champ lors du publipostage du message. Il est alors affiché "signature".
Est-ce que c'est bien la valeur correspondant à l'alimentation de ce champ ?

**Comment by cycojesus** [comment]
signature enlevée

**Comment by TestsCGI** [comment]
Ok : la donnée signature n'est plus proposée pour insertion et ce, quel que soit le type de courrier.
