### ISSUE TITLE
Test V3 - 2016 : écrire aux familles - envoi du message aux parents uniquement ?

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-publipostage#62]
Un élève peut avoir en plus de ses parents une relation créée dans l'annuaire avec un utilisateur ayant un profil Responsable d'élève et une relation de type tuteur par exemple (ex. parentbas).
Dans ce cas, est-ce que le message rédigé à l'intention des familles sera envoyé au tuteur ?
D'après les tests faits il ne serait envoyé qu'aux parents. Est-ce normal ?

**Comment by cycojesus** [comment]
remplacé par issue #105 de service-annuaire
