### ISSUE TITLE
Test V3 - 2016 : Envoi d'un message par mail KO

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-publipostage#63]
Test de l'envoi d'un message type "écrire aux élèves" ou "écrire à tous" par mail. Un des destinataires (parentbas ou eleve2bas) a été créé avec une adresse mail utilisé par le testeur. 
Aucun mail n'a été réceptionné.

**Comment by cycojesus** [comment]
transféré vers issue service-annuaire #106
