### ISSUE TITLE
Test V3 - 2016 : Retour à la page d'accueil Publipostage après avoir visualisé un pdf

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-publipostage#65]
Lorsqu'on a visualisé un fichier pdf d'un publipostage existant et que l'on souhaite ensuite revenir sur la page de gestion des publipostages, il faut en fait repasser par le portail. 
L'icône Maison n'est pas disponible et il n'y a pas de flêche retour.

**Comment by cycojesus** [comment]
sera réglé par #54

**Comment by TestsCGI** [comment]
Ouverture d'un nouvel onglet dans le navigateur pour visualiser le pdf.
L'onglet de laclasse.com reste ouvert et l'application publipostage reste disponible sans avoir à repasser par le portail.
