### ISSUE TITLE
Impossible de voir tous les publipostages sur la roue dentée de l'appli

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-publipostage#72]
Sur le compte de mme Breban (clg La Tourette), sur la roue dentée, elle a tellement de publipostages que toute la liste ne s'affiche pas... sans doute parce qu'il y a une limite d'affichage ou parce que la pagination n'a pas été prévue ? Il faut dire qu'elle ne savait pas que la roue dentée existait donc elle en faisait plein pour tester à chaque fois...

**Comment by cycojesus** [comment]
Elle en a 28, seul 20 étaient affichés, corrigé.
