### ISSUE TITLE
V4 - Génération du PDF non fonctionnelle (erreur dans le format généré)

### ISSUE THREAD

**Issue by CharlotteRizzo** [laclasse-com/service-publipostage#74]
Pour les profils personnels de direction, le pdf est généré dans une page, mais ne s'affiche pas. le message : "le type de fichier n'est pas pris encharge" ou " Le fichier ne commence pas par %pdf" s'affiche

Pour un profil administrateur d'établissement, la génération des pdf ne fonctionne pas, le message "vous n'avez pas les droits s'affiche en haut à droite de la page. (pour tous les navigateurs) - Normal?

**Comment by dlacroix** [comment]
normalement corrigé a retester
