### ISSUE TITLE
V4 - (non urgent) horaires des envois dans la page de gestion

### ISSUE THREAD

**Issue by CharlotteRizzo** [laclasse-com/service-publipostage#75]
Les horaires d'envois indiqués dans la page de gestion des publipostages est en retard de 2h par rapport.

**Comment by dlacroix** [comment]
il ne faut pas utiliser de champ de type "timestamp" et préférer "datetime" sinon, il y a des problèmes de time zone. C'est corrigé sur la dev et la prod.
