### ISSUE TITLE
V4 - la roue dentée affiche les publipostages créés par tout le monde

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-publipostage#82]
exemple : d'un compte à un autre on voit les mêmes publipostages si on clique sur la roue dentée.
![capture du 2017-08-22 16-32-10](https://user-images.githubusercontent.com/7963908/29570698-7a396e02-8757-11e7-82e0-38f7f38e3729.png)

**Comment by gwenhael-le-moine** [comment]
fixed
